import Omega.Audit.SourceMap

namespace Omega.Audit

def phaseZeroArtifacts : List String :=
  [ "lakefile.lean"
  , "lean-toolchain"
  , "Omega.lean"
  , "Omega/Core/Fib.lean"
  , "Omega/Core/Word.lean"
  , "Omega/Core/No11.lean"
  , "Omega/Folding/StableSyntax.lean"
  , "Omega/Folding/Weight.lean"
  , "Omega/Folding/Value.lean"
  , "Omega/Folding/Zeckendorf.lean"
  , "Omega/Folding/Fold.lean"
  , "Omega/Folding/Fiber.lean"
  , "Omega/Folding/InverseLimit.lean"
  , "Omega/Folding/Rewrite.lean"
  , "Omega/Folding/Defect.lean"
  , "Omega/Graph/LabeledGraph.lean"
  , "Omega/Graph/Sofic.lean"
  , "Omega/SPG/Cylinder.lean"
  , "Omega/SPG/PrefixMetric.lean"
  , "Omega/SPG/Clopen.lean"
  , "Omega/SPG/ScanErrorDiscrete.lean"
  , "Omega/SPG/ScanErrorMeasure.lean"
  , "Omega/Frontier/Assumptions.lean"
  , "Omega/Frontier/Conditional.lean"
  , "Omega/Frontier/Conjectures.lean"
  , "Omega/Frontier/Certificates.lean"
  , "Omega/Audit/SourceMap.lean" ]

def phaseOneTargets : List String :=
  [ "stable syntax"
  , "prefix closure"
  , "Fibonacci backbone"
  , "stable cardinality recurrence"
  , "Zeckendorf bridge"
  , "finite Fold interface"
  , "finite Fold fiber interface"
  , "finite Fold fiber rank/unrank interface"
  , "inverse-limit bridge"
  , "rewrite kernel"
  , "rewrite strong termination"
  , "rewrite confluence via canonical terminal forms"
  , "finite defect telescope"
  , "golden-mean sofic presentation"
  , "SPG prefix cylinder layer"
  , "SPG prefix ultrametric and clopen wrappers"
  , "SPG discrete scan error layer"
  , "SPG measure scan error layer"
  , "SPG prefix scan-error specialization layer"
  , "SPG measure purity and PMF bridge"
  , "frontier interfaces"
  , "frontier conditional wrappers"
  , "frontier SPG measure wrappers"
  , "frontier observable scan-error wrappers"
  , "frontier fold/rewrite/defect wrappers"
  , "frontier fold fiber normalization wrappers"
  , "frontier canonical certificate wrappers"
  , "frontier graph-language wrappers"
  , "frontier boundary-empty zero-error wrappers"
  , "frontier measure zero-iff wrappers"
  , "rewrite/fold/scan-error certificates"
  , "source map bootstrap" ]

end Omega.Audit
