namespace Omega.Audit

inductive EntryStatus where
  | planned
  | formalized
  | deferred
  | frontier
  deriving Repr, DecidableEq, Inhabited

structure SourceMapEntry where
  label : String
  sourcePath : String
  moduleName : String
  leanName : String
  phase : Nat
  status : EntryStatus
  deriving Repr, Inhabited

def initialEntries : List SourceMapEntry :=
  [ { label := "engine:no11-truncate"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Core.No11"
      leanName := "Omega.no11_truncate"
      phase := 0
      status := .formalized }
  , { label := "engine:x-restrict"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.StableSyntax"
      leanName := "Omega.X.restrict"
      phase := 0
      status := .formalized }
  , { label := "prop:folding-stable-syntax-fibonacci-count"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.StableSyntax"
      leanName := "Omega.X.card_eq_paperFib_succ"
      phase := 1
      status := .formalized }
  , { label := "prop:folding-stable-syntax-terminal-recursion"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.StableSyntax"
      leanName := "Omega.X.card_recurrence"
      phase := 1
      status := .formalized }
  , { label := "bridge:stable-value-zeck-indices"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.Zeckendorf"
      leanName := "Omega.X.stableValue_eq_sum_fib_zeckIndices"
      phase := 2
      status := .formalized }
  , { label := "bridge:stable-word-is-zeckendorf-rep"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.Zeckendorf"
      leanName := "Omega.X.zeckIndices_isZeckendorfRep"
      phase := 2
      status := .formalized }
  , { label := "bridge:mathlib-zeckendorf-equiv"
      sourcePath := "mathlib/Data/Nat/Fib/Zeckendorf.lean"
      moduleName := "Omega.Folding.Zeckendorf"
      leanName := "Omega.natZeckendorfEquiv"
      phase := 2
      status := .formalized }
  , { label := "def:fold-word"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fold"
      leanName := "Omega.Fold"
      phase := 3
      status := .formalized }
  , { label := "prop:fold-idempotent"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fold"
      leanName := "Omega.Fold_idempotent"
      phase := 3
      status := .formalized }
  , { label := "prop:fold-basic"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fold"
      leanName := "Omega.Fold_surjective"
      phase := 3
      status := .formalized }
  , { label := "def:fold-fiber"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.fiber"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-fiber-nonempty"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.fiber_nonempty"
      phase := 3
      status := .formalized }
  , { label := "def:fold-fiber-rank"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.rank"
      phase := 3
      status := .formalized }
  , { label := "def:fold-fiber-unrank"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.unrank"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-fiber-rank-unrank"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.rank_unrank"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-fiber-unrank-fold"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.Fold_unrankWord"
      phase := 3
      status := .formalized }
  , { label := "prop:fold-rewrite-value-preserving"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_value"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-strong-termination"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_stronglyTerminating"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-supported-normal-form"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_supported_eq_iota_normalPrefix"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-rtrans-preserves-normalprefix"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.reflTransGen_normalPrefix"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-terminal-exists"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.exists_irreducible_descendant"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-rewrite-irred-unique-on-window"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_eq_of_normalPrefix_eq"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-terminal-irred-unique"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_terminal_unique"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-terminal-irred-unique-unbounded"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_terminal_unique_unbounded"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-confluent"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_confluent"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-locally-confluent"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_locallyConfluent"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-rewrite-terminal-equals-fold"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_terminal_eq_fold"
      phase := 3
      status := .formalized }
  , { label := "cor:foldm-order-indep-bridge"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.normalPrefix_iota_eq_Fold"
      phase := 3
      status := .formalized }
  , { label := "thm:inverse-limit-golden"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.InverseLimit"
      leanName := "Omega.X.inverseLimitEquiv"
      phase := 4
      status := .formalized }
  , { label := "def:fold-local-curvature-defect"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.Defect"
      leanName := "Omega.localDefect"
      phase := 4
      status := .formalized }
  , { label := "def:fold-global-stokes-defect"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.Defect"
      leanName := "Omega.globalDefect"
      phase := 4
      status := .formalized }
  , { label := "thm:fold-discrete-stokes-defect"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.Defect"
      leanName := "Omega.globalDefect_eq_defectChain"
      phase := 4
      status := .formalized }
  , { label := "def:golden-mean-labeled-graph"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Graph.LabeledGraph"
      leanName := "Omega.Graph.LabeledGraph"
      phase := 7
      status := .formalized }
  , { label := "thm:golden-mean-sofic-presentation"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Graph.Sofic"
      leanName := "Omega.Graph.acceptsWord_goldenMean_iff_no11"
      phase := 7
      status := .formalized }
  , { label := "cor:stable-language-explicit-sofic"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Graph.Sofic"
      leanName := "Omega.Graph.stableLanguage_eq_goldenMean"
      phase := 7
      status := .formalized }
  , { label := "prop:spg-decidable-clopen"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.Clopen"
      leanName := "Omega.SPG.spg_decidableClopen"
      phase := 6
      status := .formalized }
  , { label := "def:spg-discrete-scan-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-scan-error-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-prefix-event-zero-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_eq_zero_of_prefixEvent"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-prefix-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-prefix-boundary-upper-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_le_boundaryCard_mul"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-prefix-event-empty-boundary"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixBoundaryCells_prefixEvent_eq_empty"
      phase := 6
      status := .formalized }
  , { label := "def:spg-measure-scan-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-observable-zero-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_observableEvent_eq_zero"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-boundary-upper-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_le_boundaryCard_mul"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-prefix-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-prefix-boundary-upper-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_le_boundaryCard_mul"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-prefix-event-zero-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_eq_zero_of_prefixEvent"
      phase := 6
      status := .formalized }
  , { label := "def:spg-measure-observable-purity"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.ObservablePureMeasure"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-purity-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.observablePureMeasure_iff_boundaryCellsMeasure_eq_empty"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-purity-zero-scan"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_eq_zero_of_observablePure"
      phase := 6
      status := .formalized }
  , { label := "bridge:spg-pmf-to-measure-scan-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_toMeasure_eq_scanError"
      phase := 6
      status := .formalized }
  , { label := "bridge:spg-prefix-pmf-to-measure-scan-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_toMeasure_eq_prefixScanError"
      phase := 6
      status := .formalized }
  , { label := "cond:full-generation-certifies"
      sourcePath := "sections/body/frontier/conditional.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fullGeneration_certifies"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-error-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:local-defect-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.localDefect_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:global-defect-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.globalDefect_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-step-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewriteStep_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-irreducible-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableIrreducible_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-zero-scan-certificate"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableZeroScan_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cond:generated-defect-certificate-sound"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.generatedDefectCertificate_sound"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-certificate-sound"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_certificate_sound"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-error-certificate-sound"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_certificate_sound"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-step-certificate-value"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewriteStep_certificate_value"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-certificate-idempotent"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.foldCertificate_idempotent"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-certificate-in-fiber"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.foldCertificate_inFiber"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-zero-scan-certificate-sound"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableZeroScan_certificate_sound"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-zero-scan-certificate-sound"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixZeroScan_certificate_sound"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-idempotent"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_idempotent"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-fixed-on-stable"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_fixedOnStable"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-surjective"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_surjective"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-fiber-nonempty"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_fiber_nonempty"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-fiber-unrank-sound"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_fiber_unrank_sound"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-choose-preimage-sound"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_choosePreimage_sound"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-choose-preimage-in-fiber"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_choosePreimage_inFiber"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-unrank-rank-of-eq"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_unrank_rankOfEq"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-order-independence"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_orderIndependent"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-strong-termination"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_stronglyTerminating"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-confluence"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_confluent"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-local-confluence"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_locallyConfluent"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-value-invariant"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_valueInvariant"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-irreducible-iff-stablecfg"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_irreducible_iff_stableCfg"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-irreducible-same-value-unique"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_irreducible_sameValue_unique"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-fold-irreducible"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_fold_irreducible"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-terminal-exists"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_terminal_exists"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-terminal-unique"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_terminal_unique"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-terminal-equals-fold"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_terminal_equals_fold"
      phase := 8
      status := .formalized }
  , { label := "cond:inverse-limit-presentation"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.inverseLimitPresentation"
      phase := 8
      status := .formalized }
  , { label := "cond:defect-local-as-global-step"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.localDefect_as_globalStep"
      phase := 8
      status := .formalized }
  , { label := "cond:defect-recursive-step"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.globalDefect_recursive"
      phase := 8
      status := .formalized }
  , { label := "cond:defect-telescope"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.defect_telescope"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-language-sofic"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableLanguage_sofic"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-implies-sofic"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stable_implies_sofic"
      phase := 8
      status := .formalized }
  , { label := "cond:sofic-implies-stable"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.sofic_implies_stable"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-language-set-sofic"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableLanguage_set_sofic"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-point-sofic"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stablePoint_sofic"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-ball-cylinder"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixBall_is_cylinder"
      phase := 8
      status := .formalized }
  , { label := "cond:cylinder-closed-ball"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.cylinder_is_closedBall"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-ball-closed-ball"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixBall_is_closedBall"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-decidable-clopen"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_decidableClopen"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-determined-clopen"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixDetermined_clopen"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-determined-from-wordset"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixDetermined_iff_fromWordSet"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-event-boundary-empty-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableEvent_boundaryEmpty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-event-zero-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableEvent_zero_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-boundary-decomposition-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_boundary_decomposition_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-boundary-mass-bound-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_boundary_mass_bound_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-boundary-card-bound-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_boundary_card_bound_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-zero-boundary-empty-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_zero_of_boundaryEmpty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-pure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_pure_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-boundary-empty-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_boundaryEmpty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-zero-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_zero_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-error-zero-boundary-empty-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_zero_of_boundaryEmpty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-event-observable-pure-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableEvent_observablePure_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-event-boundary-empty-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableEvent_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-event-zero-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableEvent_zero_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-pure-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_pure_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-boundary-empty-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-zero-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_zero_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-observable-pure-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_observablePure_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-pure-iff-boundary-empty-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observablePure_iff_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-zero-iff-observable-pure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_zero_iff_observablePure_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-zero-iff-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_zero_iff_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-observable-pure-iff-boundary-empty-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixObservablePure_iff_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-measure-zero-iff-observable-pure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_zero_iff_observablePure_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-measure-zero-iff-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_zero_iff_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-observable-pure-zero-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixObservablePure_zero_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-pure-zero-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observablePure_zero_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_measure_boundary_decomposition"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-boundary-mass-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_measure_boundary_mass_bound"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-boundary-card-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_measure_boundary_card_bound"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-zero-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_zero_of_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-measure-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_measure_boundary_decomposition"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-measure-boundary-mass-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_measure_boundary_mass_bound"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-measure-boundary-card-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_measure_boundary_card_bound"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-measure-zero-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_zero_of_boundaryEmpty_measure"
      phase := 8
      status := .formalized }
  , { label := "bridge:prefix-scan-measure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "bridge:boundary-cells-measure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.boundaryCells_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "bridge:prefix-boundary-cells-measure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixBoundaryCells_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "bridge:scan-measure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "bridge:observable-event-measure-discrete-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableEvent_zero_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "bridge:prefix-event-measure-discrete-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_pure_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-zero-scan-certificate"
      sourcePath := "sections/body/frontier/conditional.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixZeroScan_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cert:rewrite-step"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.RewriteStepCertificate.Valid"
      phase := 8
      status := .formalized }
  , { label := "cert:fold"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.FoldCertificate.Valid"
      phase := 8
      status := .formalized }
  , { label := "cert:scan-error"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.ScanErrorCertificate.Valid"
      phase := 8
      status := .formalized }
  , { label := "cert:prefix-zero-scan"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.PrefixZeroScanCertificate.Valid"
      phase := 8
      status := .formalized }
  , { label := "def:spg-discrete-observable-purity"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.ObservablePure"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-discrete-purity-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.observablePure_iff_boundaryCells_eq_empty"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-discrete-zero-iff-pure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_eq_zero_iff_observablePure"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-discrete-zero-iff-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_eq_zero_iff_boundaryCells_eq_empty"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-discrete-complement-symmetry"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_compl"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-discrete-empty-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_empty"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-discrete-univ-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_univ"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-complement-symmetry"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_compl"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-empty-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_empty"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-univ-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_univ"
      phase := 6
      status := .formalized }
  , { label := "cond:scan-error-complement-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_compl_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-empty-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_empty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-univ-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_univ_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:observable-event-pure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observableEvent_observablePure_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:discrete-pure-iff-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observablePure_iff_boundaryEmpty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:discrete-zero-iff-pure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_zero_iff_observablePure_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:discrete-zero-iff-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_zero_iff_boundaryEmpty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-complement-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_compl_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-empty-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_empty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-univ-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_univ_measure"
      phase := 8
      status := .formalized }
  , { label := "thm:spg-discrete-prefix-zero-iff-pure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_eq_zero_iff_observablePure"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-discrete-prefix-zero-iff-boundary-empty"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_eq_zero_iff_boundaryCells_eq_empty"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-discrete-prefix-complement"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_compl"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-discrete-prefix-empty-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_empty"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-discrete-prefix-univ-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_univ"
      phase := 6
      status := .formalized }
  , { label := "bridge:spg-purity-pmf-to-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.observablePureMeasure_toMeasure_iff_observablePure"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-prefix-complement"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_compl"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-prefix-empty-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_empty"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-prefix-univ-zero"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_univ"
      phase := 6
      status := .formalized }
  , { label := "ineq:sum-min-le-min-sum"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.sum_min_le_min_sum"
      phase := 6
      status := .formalized }
  , { label := "cond:prefix-event-pure-discrete-obs"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_observablePure_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-zero-iff-pure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_zero_iff_observablePure_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-zero-iff-boundary-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_zero_iff_boundaryEmpty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-compl-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_compl_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-empty-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_empty_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-univ-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_univ_discrete"
      phase := 8
      status := .formalized }
  , { label := "bridge:cond-purity-pmf-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observablePure_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-compl-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_compl_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-empty-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_empty_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-univ-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_univ_measure"
      phase := 8
      status := .formalized }
  , { label := "thm:spg-observation-refinement-monotonicity"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_antitone_of_refines"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-prefix-scan-error-monotonicity"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_antitone"
      phase := 6
      status := .formalized }
  , { label := "cond:observation-refinement-monotonicity"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_antitone_of_refines"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-scan-error-monotonicity"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_antitone"
      phase := 8
      status := .formalized }
  , { label := "thm:spg-cell-event-mass-partition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.cellEventMass_sum_eq_setMass"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-cell-compl-mass-partition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.cellComplMass_sum_eq_setMass_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-cell-mass-total-partition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.cellMass_sum_eq_setMass_univ"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-scan-error-bayes-optimality"
      sourcePath := "sections/body/spg/prop__spg-clarity-bayes-optimality.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_le_min_setMass"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-scan-error-bayes-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_le_min"
      phase := 6
      status := .formalized }
  , { label := "cond:cell-event-mass-partition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.cellEventMass_partition"
      phase := 8
      status := .formalized }
  , { label := "cond:cell-compl-mass-partition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.cellComplMass_partition"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-bayes-bound"
      sourcePath := "sections/body/spg/prop__spg-clarity-bayes-optimality.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_bayes_bound"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-scan-error-bayes-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_measure_bayes_bound"
      phase := 8
      status := .formalized }
  , { label := "def:boundary-cylinder-count"
      sourcePath := "sections/body/spg/def__spg-boundary-cylinder-dimension.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.boundaryCylinderCount"
      phase := 6
      status := .formalized }
  , { label := "def:prefix-boundary-cylinder-count"
      sourcePath := "sections/body/spg/def__spg-boundary-cylinder-dimension.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixBoundaryCylinderCount"
      phase := 6
      status := .formalized }
  , { label := "thm:boundary-count-zero-iff-pure"
      sourcePath := "sections/body/spg/cor__spg-clarity-monotonicity.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.boundaryCylinderCount_eq_zero_iff_observablePure"
      phase := 6
      status := .formalized }
  , { label := "thm:scan-error-zero-iff-boundary-count-zero"
      sourcePath := "sections/body/spg/cor__spg-clarity-monotonicity.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_eq_zero_iff_boundaryCylinderCount_eq_zero"
      phase := 6
      status := .formalized }
  , { label := "thm:boundary-count-pmf-bridge"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.boundaryCylinderCount_toMeasure_eq"
      phase := 6
      status := .formalized }
  , { label := "cond:stable-syntax-fibonacci-cardinality"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableSyntax_card_eq_fibonacci"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-syntax-fibonacci-recurrence"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableSyntax_card_recurrence"
      phase := 8
      status := .formalized }
  , { label := "cond:zeckendorf-valid"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableWord_zeckendorf_valid"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-value-fibonacci-sum"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableValue_eq_fibonacci_weighted_sum"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-fiber-card-pos"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_fiber_card_pos"
      phase := 8
      status := .formalized }
  , { label := "cond:boundary-count-zero-iff-pure"
      sourcePath := "sections/body/spg/def__spg-boundary-cylinder-dimension.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.boundaryCylinderCount_zero_iff_pure_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:scan-error-zero-iff-boundary-count-zero"
      sourcePath := "sections/body/spg/cor__spg-clarity-monotonicity.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_zero_iff_boundaryCylinderCount_zero_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:boundary-count-pmf-bridge"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.boundaryCylinderCount_measure_discrete_bridge"
      phase := 8
      status := .formalized }
  , { label := "cond:measure-antitone-observation-refinement"
      sourcePath := "sections/body/spg/cor__spg-clarity-monotonicity.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.scanError_measure_antitone_via_bridge"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-measure-antitone"
      sourcePath := "sections/body/spg/cor__spg-clarity-monotonicity.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixScanError_measure_antitone_via_bridge"
      phase := 8
      status := .formalized }
  , { label := "thm:cell-partition-identity"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.cellEventMass_add_cellComplMass_eq_cellMass"
      phase := 6
      status := .formalized }
  , { label := "cond:stable-value-injective"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableValue_injective"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-value-ofnat-roundtrip"
      sourcePath := "sections/body/arithmetic/sec__emergent-stable-arithmetic.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableValue_ofNat_roundtrip"
      phase := 8
      status := .formalized }
  , { label := "cond:cell-partition-identity"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.cellEventMass_add_cellComplMass_partition"
      phase := 8
      status := .formalized }
  -- Fiber partition & word cardinality
  , { label := "thm:word-card"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.Word_card"
      phase := 1
      status := .formalized }
  , { label := "thm:fiber-card-sum"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.fiber_card_sum"
      phase := 3
      status := .formalized }
  , { label := "thm:fiber-card-sum-eq-pow"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.fiber_card_sum_eq_pow"
      phase := 3
      status := .formalized }
  , { label := "cond:fiber-card-partition"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fiber_card_partition"
      phase := 9
      status := .formalized }
  , { label := "cond:fiber-card-partition-pow"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fiber_card_partition_pow"
      phase := 9
      status := .formalized }
  -- Phase 9: complement symmetry & cell-level measure bounds
  , { label := "thm:observable-pure-compl-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.observablePure_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:boundary-cells-compl-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.boundaryCells_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:prefix-boundary-cells-compl-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixBoundaryCells_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:cell-event-measure-le"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.cellEventMeasure_le_cellMeasure"
      phase := 6
      status := .formalized }
  , { label := "thm:cell-compl-measure-le"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.cellComplMeasure_le_cellMeasure"
      phase := 6
      status := .formalized }
  , { label := "thm:cell-partition-identity-measure"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.cellEventMeasure_add_cellComplMeasure_eq_cellMeasure"
      phase := 6
      status := .formalized }
  , { label := "thm:observable-pure-compl-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.observablePureMeasure_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:boundary-cells-compl-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.boundaryCellsMeasure_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:boundary-cylinder-count-compl"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.boundaryCylinderCount_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:prefix-boundary-cells-compl-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixBoundaryCellsMeasure_compl"
      phase := 6
      status := .formalized }
  , { label := "thm:prefix-boundary-cylinder-count-compl"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixBoundaryCylinderCount_compl"
      phase := 6
      status := .formalized }
  , { label := "cond:observable-pure-compl-symmetric-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observablePure_compl_symmetric_discrete"
      phase := 9
      status := .formalized }
  , { label := "cond:boundary-cells-compl-symmetric-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.boundaryCells_compl_symmetric_discrete"
      phase := 9
      status := .formalized }
  , { label := "cond:prefix-boundary-cells-compl-symmetric-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixBoundaryCells_compl_symmetric_discrete"
      phase := 9
      status := .formalized }
  , { label := "cond:observable-pure-compl-symmetric-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.observablePure_compl_symmetric_measure"
      phase := 9
      status := .formalized }
  , { label := "cond:boundary-cells-compl-symmetric-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.boundaryCells_compl_symmetric_measure"
      phase := 9
      status := .formalized }
  , { label := "cond:boundary-cylinder-count-compl-symmetric-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.boundaryCylinderCount_compl_symmetric_measure"
      phase := 9
      status := .formalized }
  , { label := "cond:prefix-boundary-cells-compl-symmetric-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixBoundaryCells_compl_symmetric_measure"
      phase := 9
      status := .formalized }
  , { label := "cond:prefix-boundary-cylinder-count-compl-symmetric-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixBoundaryCylinderCount_compl_symmetric_measure"
      phase := 9
      status := .formalized }
  , { label := "cond:cell-event-measure-le"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.cellEventMeasure_le_cell"
      phase := 9
      status := .formalized }
  , { label := "cond:cell-compl-measure-le"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.cellComplMeasure_le_cell"
      phase := 9
      status := .formalized }
  , { label := "cond:cell-partition-identity-measure"
      sourcePath := "sections/body/spg/prop__spg-cylinder-decomposition.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.cellPartition_identity_measure"
      phase := 9
      status := .formalized }
  -- Phase 10: Carry Defect (Plan 3)
  , { label := "aux:paperFib-add-fib-eq"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.paperFib_add_fib_eq"
      phase := 10
      status := .formalized }
  , { label := "aux:fib-sub-eq"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.fib_sub_eq"
      phase := 10
      status := .formalized }
  , { label := "aux:fib-lt-paperFib-succ"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.fib_lt_paperFib_succ"
      phase := 10
      status := .formalized }
  , { label := "thm:pom-stable-addition-carry-defect-unique-element"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.stableValue_restrict_stableAdd_carry"
      phase := 10
      status := .formalized }
  , { label := "thm:pom-stable-addition-carry-defect-unique-element-word"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.restrict_stableAdd_carry_defect"
      phase := 10
      status := .formalized }
  , { label := "cor:pom-carry-defect-m6-anchor-8-34"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.carryElement_m6_value"
      phase := 10
      status := .formalized }
  , { label := "cor:pom-carry-defect-m5-value"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.carryElement_m5_value"
      phase := 10
      status := .formalized }
  , { label := "cor:pom-carry-defect-m7-value"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.carryElement_m7_value"
      phase := 10
      status := .formalized }
  , { label := "prop:pom-carry-element-nonzero"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.CarryDefect"
      leanName := "Omega.X.carryElement_ne_zero"
      phase := 10
      status := .formalized }
  -- Phase 11: FiberFusion (Plan 7)
  -- lem:pom-fib-fusion-submultiplicativity → fib_fusion, fib_prod_lt_fib_fusion,
  --   fib_fusion_lt_fib_sum, fib_prod_lt_fib_sum (Omega/Folding/FiberFusion.lean)
  -- 状态: 已形式化, 审核通过 2026-03-22
  , { label := "lem:pom-fib-fusion-submultiplicativity"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_fusion"
      phase := 11
      status := .formalized }
  , { label := "lem:pom-fib-fusion-submultiplicativity-prod-lt-fusion"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_prod_lt_fib_fusion"
      phase := 11
      status := .formalized }
  , { label := "lem:pom-fib-fusion-submultiplicativity-fusion-lt-sum"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_fusion_lt_fib_sum"
      phase := 11
      status := .formalized }
  , { label := "lem:pom-fib-fusion-submultiplicativity-prod-lt-sum"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_prod_lt_fib_sum"
      phase := 11
      status := .formalized }
  -- cor:pom-fib-component-fusion-gain → fib_component_fusion_lt,
  --   fib_component_fusion_gain, fib_component_fusion_gain_lower,
  --   fib_component_fusion_gain_ge (Omega/Folding/FiberFusion.lean)
  -- 状态: 已形式化, 审核通过 2026-03-22
  , { label := "cor:pom-fib-component-fusion-gain"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_component_fusion_lt"
      phase := 11
      status := .formalized }
  , { label := "cor:pom-fib-component-fusion-gain-bound"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_component_fusion_gain"
      phase := 11
      status := .formalized }
  , { label := "cor:pom-fib-component-fusion-gain-lower"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_component_fusion_gain_lower"
      phase := 11
      status := .formalized }
  , { label := "cor:pom-fib-component-fusion-gain-ge"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.FiberFusion"
      leanName := "Omega.X.fib_component_fusion_gain_ge"
      phase := 11
      status := .formalized }
  -- Phase 12: MaxFiber (Plan 8 partial)
  -- def:pom-top-fiber-spectrum → X.maxFiberMultiplicity (Omega/Folding/MaxFiber.lean:15)
  -- thm:pom-max-fiber (partial) → X.maxFiberMultiplicity_achieved (Omega/Folding/MaxFiber.lean:20)
  --                             → X.fiberMultiplicity_le_max    (Omega/Folding/MaxFiber.lean:27)
  --                             → X.maxFiberMultiplicity_pos    (Omega/Folding/MaxFiber.lean:32)
  -- 状态: 部分形式化（定义+基本性质已审核），闭式 D_{2k}=F_{k+2}, D_{2k+1}=2F_{k+1} 待实现
  -- 审核通过 2026-03-22
  , { label := "def:pom-top-fiber-spectrum"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.MaxFiber"
      leanName := "Omega.X.maxFiberMultiplicity"
      phase := 12
      status := .formalized }
  , { label := "thm:pom-max-fiber-achieved"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.MaxFiber"
      leanName := "Omega.X.maxFiberMultiplicity_achieved"
      phase := 12
      status := .formalized }
  , { label := "thm:pom-max-fiber-le-max"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.MaxFiber"
      leanName := "Omega.X.fiberMultiplicity_le_max"
      phase := 12
      status := .formalized }
  , { label := "thm:pom-max-fiber-pos"
      sourcePath := "sections/body/pom/subsec__pom-fiber-spectrum.tex"
      moduleName := "Omega.Folding.MaxFiber"
      leanName := "Omega.X.maxFiberMultiplicity_pos"
      phase := 12
      status := .formalized }
  -- Phase 13: ModularTower (Plan 4)
  -- thm:pom-modular-tower → modularProject_eq_restrict, modularProject_stableAdd_carry,
  --   stableValue_modularProject_stableMul, stableValue_restrict_stableMul,
  --   restrict_comp_restrict, tower_compatible, restrict_tower_transitivity,
  --   modularProject_stableZero, stableValue_modularProject_stableAdd_carry,
  --   stableValue_modularProject_compose, carryIndicator_comm,
  --   modularProject_tower_surjective (Omega/Folding/ModularTower.lean)
  -- 状态: 已形式化, 审核通过 2026-03-22
  , { label := "thm:pom-modular-project-eq-restrict"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.modularProject_eq_restrict"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-modular-project-carry-defect"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.modularProject_stableAdd_carry"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-modular-project-mul-value"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.stableValue_modularProject_stableMul"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-restrict-mul-value"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.stableValue_restrict_stableMul"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-restrict-comp-restrict"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.restrict_comp_restrict"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-tower-compatible"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.tower_compatible"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-restrict-tower-transitivity"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.restrict_tower_transitivity"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-modular-project-zero"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.modularProject_stableZero"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-modular-project-add-carry-value"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.stableValue_modularProject_stableAdd_carry"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-modular-project-compose-value"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.stableValue_modularProject_compose"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-carry-indicator-comm"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.carryIndicator_comm"
      phase := 13
      status := .formalized }
  , { label := "thm:pom-modular-tower-surjective"
      sourcePath := "sections/body/pom/subsec__pom-stable-addition.tex"
      moduleName := "Omega.Folding.ModularTower"
      leanName := "Omega.X.modularProject_tower_surjective"
      phase := 13
      status := .formalized } ]

end Omega.Audit
