namespace Omega.Audit

inductive EntryStatus where
  | planned
  | formalized
  | deferred
  | frontier
  deriving Repr, DecidableEq, Inhabited

structure SourceMapEntry where
  label : String
  sourcePath : String
  moduleName : String
  leanName : String
  phase : Nat
  status : EntryStatus
  deriving Repr, Inhabited

def initialEntries : List SourceMapEntry :=
  [ { label := "engine:no11-truncate"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Core.No11"
      leanName := "Omega.no11_truncate"
      phase := 0
      status := .formalized }
  , { label := "engine:x-restrict"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.StableSyntax"
      leanName := "Omega.X.restrict"
      phase := 0
      status := .formalized }
  , { label := "prop:folding-stable-syntax-fibonacci-count"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.StableSyntax"
      leanName := "Omega.X.card_eq_paperFib_succ"
      phase := 1
      status := .formalized }
  , { label := "prop:folding-stable-syntax-terminal-recursion"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.StableSyntax"
      leanName := "Omega.X.card_recurrence"
      phase := 1
      status := .formalized }
  , { label := "bridge:stable-value-zeck-indices"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.Zeckendorf"
      leanName := "Omega.X.stableValue_eq_sum_fib_zeckIndices"
      phase := 2
      status := .formalized }
  , { label := "bridge:stable-word-is-zeckendorf-rep"
      sourcePath := "sections/body/folding/subsec__folding-fibonacci-stable-syntax.tex"
      moduleName := "Omega.Folding.Zeckendorf"
      leanName := "Omega.X.zeckIndices_isZeckendorfRep"
      phase := 2
      status := .formalized }
  , { label := "bridge:mathlib-zeckendorf-equiv"
      sourcePath := "mathlib/Data/Nat/Fib/Zeckendorf.lean"
      moduleName := "Omega.Folding.Zeckendorf"
      leanName := "Omega.natZeckendorfEquiv"
      phase := 2
      status := .formalized }
  , { label := "def:fold-word"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fold"
      leanName := "Omega.Fold"
      phase := 3
      status := .formalized }
  , { label := "prop:fold-idempotent"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fold"
      leanName := "Omega.Fold_idempotent"
      phase := 3
      status := .formalized }
  , { label := "prop:fold-basic"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fold"
      leanName := "Omega.Fold_surjective"
      phase := 3
      status := .formalized }
  , { label := "def:fold-fiber"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.fiber"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-fiber-nonempty"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.fiber_nonempty"
      phase := 3
      status := .formalized }
  , { label := "def:fold-fiber-rank"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.rank"
      phase := 3
      status := .formalized }
  , { label := "def:fold-fiber-unrank"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.unrank"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-fiber-rank-unrank"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.rank_unrank"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-fiber-unrank-fold"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Fiber"
      leanName := "Omega.X.Fold_unrankWord"
      phase := 3
      status := .formalized }
  , { label := "prop:fold-rewrite-value-preserving"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_value"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-strong-termination"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_stronglyTerminating"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-supported-normal-form"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_supported_eq_iota_normalPrefix"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-rtrans-preserves-normalprefix"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.reflTransGen_normalPrefix"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-terminal-exists"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.exists_irreducible_descendant"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-rewrite-irred-unique-on-window"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_eq_of_normalPrefix_eq"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-terminal-irred-unique"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_terminal_unique"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-terminal-irred-unique-unbounded"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_terminal_unique_unbounded"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-confluent"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_confluent"
      phase := 3
      status := .formalized }
  , { label := "thm:fold-rewrite-locally-confluent"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.step_locallyConfluent"
      phase := 3
      status := .formalized }
  , { label := "cor:fold-rewrite-terminal-equals-fold"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.irreducible_terminal_eq_fold"
      phase := 3
      status := .formalized }
  , { label := "cor:foldm-order-indep-bridge"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Folding.Rewrite"
      leanName := "Omega.Rewrite.normalPrefix_iota_eq_Fold"
      phase := 3
      status := .formalized }
  , { label := "thm:inverse-limit-golden"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.InverseLimit"
      leanName := "Omega.X.inverseLimitEquiv"
      phase := 4
      status := .formalized }
  , { label := "def:fold-local-curvature-defect"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.Defect"
      leanName := "Omega.localDefect"
      phase := 4
      status := .formalized }
  , { label := "def:fold-global-stokes-defect"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.Defect"
      leanName := "Omega.globalDefect"
      phase := 4
      status := .formalized }
  , { label := "thm:fold-discrete-stokes-defect"
      sourcePath := "sections/body/folding/subsec__folding-multiscale.tex"
      moduleName := "Omega.Folding.Defect"
      leanName := "Omega.globalDefect_eq_defectChain"
      phase := 4
      status := .formalized }
  , { label := "def:golden-mean-labeled-graph"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Graph.LabeledGraph"
      leanName := "Omega.Graph.LabeledGraph"
      phase := 7
      status := .formalized }
  , { label := "thm:golden-mean-sofic-presentation"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Graph.Sofic"
      leanName := "Omega.Graph.acceptsWord_goldenMean_iff_no11"
      phase := 7
      status := .formalized }
  , { label := "cor:stable-language-explicit-sofic"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Graph.Sofic"
      leanName := "Omega.Graph.stableLanguage_eq_goldenMean"
      phase := 7
      status := .formalized }
  , { label := "prop:spg-decidable-clopen"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.Clopen"
      leanName := "Omega.SPG.spg_decidableClopen"
      phase := 6
      status := .formalized }
  , { label := "def:spg-discrete-scan-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-scan-error-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.scanError_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-prefix-event-zero-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_eq_zero_of_prefixEvent"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-prefix-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-prefix-boundary-upper-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixScanError_le_boundaryCard_mul"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-prefix-event-empty-boundary"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorDiscrete"
      leanName := "Omega.SPG.prefixBoundaryCells_prefixEvent_eq_empty"
      phase := 6
      status := .formalized }
  , { label := "def:spg-measure-scan-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-observable-zero-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_observableEvent_eq_zero"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-boundary-upper-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_le_boundaryCard_mul"
      phase := 6
      status := .formalized }
  , { label := "thm:spg-measure-prefix-boundary-decomposition"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_eq_sum_boundary"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-prefix-boundary-upper-bound"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_le_boundaryCard_mul"
      phase := 6
      status := .formalized }
  , { label := "cor:spg-measure-prefix-event-zero-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.prefixScanErrorMeasure_eq_zero_of_prefixEvent"
      phase := 6
      status := .formalized }
  , { label := "bridge:spg-pmf-to-measure-scan-error"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.SPG.ScanErrorMeasure"
      leanName := "Omega.SPG.scanErrorMeasure_toMeasure_eq_scanError"
      phase := 6
      status := .formalized }
  , { label := "cond:full-generation-certifies"
      sourcePath := "sections/body/frontier/conditional.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fullGeneration_certifies"
      phase := 8
      status := .formalized }
  , { label := "cond:fold-order-independence"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.fold_orderIndependent"
      phase := 8
      status := .formalized }
  , { label := "cond:rewrite-terminal-unique"
      sourcePath := "sections/body/folding/subsec__folding-map.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.rewrite_terminal_unique"
      phase := 8
      status := .formalized }
  , { label := "cond:stable-language-sofic"
      sourcePath := "sections/body/symbolic/sofic.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.stableLanguage_sofic"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-pure-discrete"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_pure_discrete"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-event-pure-measure"
      sourcePath := "sections/body/spg/sec__spg.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixEvent_pure_measure"
      phase := 8
      status := .formalized }
  , { label := "cond:prefix-zero-scan-certificate"
      sourcePath := "sections/body/frontier/conditional.tex"
      moduleName := "Omega.Frontier.Conditional"
      leanName := "Omega.Frontier.prefixZeroScan_hasCertificate"
      phase := 8
      status := .formalized }
  , { label := "cert:rewrite-step"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.RewriteStepCertificate.Valid"
      phase := 8
      status := .formalized }
  , { label := "cert:fold"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.FoldCertificate.Valid"
      phase := 8
      status := .formalized }
  , { label := "cert:scan-error"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.ScanErrorCertificate.Valid"
      phase := 8
      status := .formalized }
  , { label := "cert:prefix-zero-scan"
      sourcePath := "sections/body/frontier/certificates.tex"
      moduleName := "Omega.Frontier.Certificates"
      leanName := "Omega.Frontier.PrefixZeroScanCertificate.Valid"
      phase := 8
      status := .formalized } ]

end Omega.Audit
