#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Irreducibility certificates for the resonance-window collision moment characteristic polynomials P_q
for q=9..17.

We build P_q from the audited minimal integer recurrences in:
  sections/generated/tab_fold_collision_moment_recursions_9_17.tex
and certify irreducibility over Q by exhibiting a prime p such that P_q mod p is irreducible.

Outputs:
  - artifacts/export/fold_collision_moment_charpoly_irreducible_q9_17.json
  - sections/generated/tab_fold_collision_moment_charpoly_irreducible_certificate_q9_17.tex
"""

from __future__ import annotations

import json
import warnings
from dataclasses import asdict, dataclass

import sympy as sp

from common_paths import export_dir, generated_dir

try:
    from sympy.utilities.exceptions import SymPyDeprecationWarning

    warnings.filterwarnings("ignore", category=SymPyDeprecationWarning)
except Exception:
    pass


@dataclass(frozen=True)
class Row:
    q: int
    d: int
    irreducible_over_Q: bool
    p_irr: int
    degs_mod_p_irr: list[int]


REC_C: dict[int, tuple[int, ...]] = {
    9: (2, 62, 386, 2819, 62, 900, -450),
    10: (2, 96, 830, 7945, 2, 1852, -830, 4, -4),
    11: (2, 153, 1740, 21249, -9432, -86213, -1484, -18348, 9174),
    12: (2, 243, 3608, 56447, -61236, -667319, 3608, -9582, 61242, 15404, -7216, 8, -8),
    13: (2, 388, 7414, 148038, -317916, -4165856, 136252, 1565891, 318938, 289380, -144690),
    14: (2, 621, 15140, 385463, -1443744, -22761161, 15140, -2116566, 1443750, 63044, -30280, 8, -8),
    15: (2, 1000, 30766, 994458, -6188172, -119408756, 8289820, 134208623, 6186122, 16637076, -8318538),
    16: (2, 1611, 62312, 2559407, -24862788, -585266591, 62312, -44606766, 24862794, 255692, -124624, 8, -8),
    17: (2, 2599, 125872, 6569850, -96034590, -2764163954, -643026032, -15022392733, 769974566, 15329386299, 642908352, 1347896340, -673948170),
}


def poly_Pq(q: int) -> sp.Poly:
    lam = sp.Symbol("lam")
    cs = REC_C[q]
    d = len(cs)
    expr = lam**d
    for i, c in enumerate(cs, start=1):
        expr -= sp.Integer(c) * lam ** (d - i)
    return sp.Poly(expr, lam, domain=sp.ZZ)


def is_irreducible_mod_p(poly: sp.Poly, p: int) -> tuple[bool, list[int]]:
    lam = poly.gens[0]
    poly_p = sp.Poly(poly.as_expr(), lam, modulus=p)
    fac = sp.factor_list(poly_p)[1]
    degs = [f.degree() for f, _e in fac]
    irreducible = len(fac) == 1 and degs[0] == poly.degree() and fac[0][1] == 1
    return irreducible, degs


def main() -> None:
    primes = list(sp.primerange(2, 300))
    rows: list[Row] = []

    for q in range(9, 18):
        P = poly_Pq(q)
        d = P.degree()

        # Over QQ: factor_list returns [(poly,exp)].
        flQ = sp.factor_list(P.as_expr())[1]
        irreducible_over_Q = len(flQ) == 1 and flQ[0][0].as_poly(P.gens[0]).degree() == d and flQ[0][1] == 1

        p_irr = None
        degs = None
        for p in primes:
            ok, degs_p = is_irreducible_mod_p(P, p)
            if ok:
                p_irr = p
                degs = degs_p
                break
        assert p_irr is not None and degs is not None

        rows.append(Row(q=q, d=d, irreducible_over_Q=irreducible_over_Q, p_irr=p_irr, degs_mod_p_irr=degs))

    export_path = export_dir() / "fold_collision_moment_charpoly_irreducible_q9_17.json"
    export_path.write_text(json.dumps([asdict(r) for r in rows], indent=2, sort_keys=True), encoding="utf-8")

    tex = []
    tex.append(r"% Auto-generated by scripts/exp_fold_collision_moment_charpoly_irreducible_q9_17.py")
    tex.append(r"\begin{table}[H]")
    tex.append(r"\centering")
    tex.append(r"\scriptsize")
    tex.append(r"\caption{Irreducibility certificates for the resonance-window Fold collision moment characteristic polynomials $P_q(\lambda)$ for $q=9,\dots,17$. We list a prime $p_{\mathrm{irr}}$ such that $P_q\bmod p_{\mathrm{irr}}$ is irreducible (degrees shown as a factor-degree tuple).}")
    tex.append(r"\label{tab:fold_collision_moment_charpoly_irreducible_certificate_q9_17}")
    tex.append(r"\begin{tabular}{r r r l}")
    tex.append(r"\toprule")
    tex.append(r"$q$ & $d_q$ & $p_{\mathrm{irr}}$ & degs mod $p_{\mathrm{irr}}$\\")
    tex.append(r"\midrule")
    for r in rows:
        tex.append(f"{r.q} & {r.d} & {r.p_irr} & ({','.join(map(str, r.degs_mod_p_irr))})\\\\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")
    tex.append("")
    (generated_dir() / "tab_fold_collision_moment_charpoly_irreducible_certificate_q9_17.tex").write_text(
        "\n".join(tex), encoding="utf-8"
    )


if __name__ == "__main__":
    main()

