#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Export completed primitive polynomials \\hat p_n(s) for the weighted sync-kernel.

We use the completion variables:
  u = r^2,  s = r + r^{-1},
and define the completed primitive polynomial
  \\hat p_n(s) := r^{-n} p_n(r^2),
which is invariant under r -> 1/r and thus lies in Z[s].

This script outputs:
  - sections/generated/tab_sync_kernel_weighted_primitive_completed.tex
  - sections/generated/eq_sync_kernel_weighted_primitive_pn_first10.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict

import sympy as sp

from common_paths import generated_dir
from exp_sync_kernel_weighted_pressure import STATES, build_edges


def chebyshev_C(k: int, s: sp.Symbol) -> sp.Expr:
    """C_k(s) = r^k + r^{-k} with s = r + r^{-1} (integer polynomial)."""
    if k == 0:
        return sp.Integer(2)
    if k == 1:
        return s
    c0, c1 = sp.Integer(2), s
    for _ in range(2, k + 1):
        c0, c1 = c1, sp.expand(s * c1 - c0)
    return c1


def completed_poly_from_pn(n: int, pn_u: sp.Expr) -> sp.Expr:
    r = sp.Symbol("r")
    s = sp.Symbol("s")
    u = sp.Symbol("u")

    expr = sp.expand(r ** (-n) * pn_u.subs(u, r**2))
    coeffs: Dict[int, sp.Expr] = {}
    for term in sp.Add.make_args(expr):
        c, e = term.as_coeff_exponent(r)
        if not e.is_Integer:
            raise ValueError(f"Non-integer exponent in term: {term}")
        ei = int(e)
        coeffs[ei] = coeffs.get(ei, 0) + c

    poly_s = sp.Integer(0)
    used = set()
    for e in sorted(coeffs.keys(), key=lambda x: abs(x)):
        if e in used:
            continue
        if e == 0:
            poly_s += coeffs[e]
            used.add(0)
            continue
        if sp.simplify(coeffs.get(e, 0) - coeffs.get(-e, 0)) != 0:
            raise ValueError(f"Not symmetric under r->1/r at n={n}, exponent={e}")
        poly_s += coeffs[e] * chebyshev_C(abs(e), s)
        used.add(e)
        used.add(-e)
    return sp.expand(poly_s)


def _build_B_u(u: sp.Symbol) -> sp.Matrix:
    """Build the 10x10 weighted adjacency matrix B(u)=B0+u B1 (symbolic in u)."""
    idx = {s: i for i, s in enumerate(STATES)}
    n = len(STATES)
    B = sp.zeros(n, n)
    edges = build_edges()
    for edge in edges:
        i = idx[edge.src]
        j = idx[edge.dst]
        B[i, j] += sp.Integer(1) if edge.e == 0 else u
    return B


def _trace_polys(Bu: sp.Matrix, N: int, u: sp.Symbol) -> Dict[int, sp.Expr]:
    """Return a_n(u)=Tr(B(u)^n) for n=1..N."""
    n = Bu.shape[0]
    M = sp.eye(n)
    out: Dict[int, sp.Expr] = {}
    for k in range(1, N + 1):
        M = sp.expand(M * Bu)
        out[k] = sp.expand(sp.trace(M))
    return out


def _primitive_polys_from_traces(a: Dict[int, sp.Expr], N: int, u: sp.Symbol) -> Dict[int, sp.Expr]:
    """Return p_n(u) from a_n(u) via Witt/Möbius inversion."""
    p: Dict[int, sp.Expr] = {}
    for n in range(1, N + 1):
        acc = sp.Integer(0)
        for d in sp.divisors(n):
            mu = sp.mobius(d)
            if mu == 0:
                continue
            acc += sp.Integer(mu) * a[n // d].subs(u, u**d)
        pn = sp.expand(acc / sp.Integer(n))
        # Sanity: integrality in Z[u]
        poly = sp.Poly(pn, u)
        if any(c.q != 1 for c in poly.all_coeffs()):
            raise ValueError(f"Non-integer coefficients in p_{n}(u): {pn}")
        p[n] = pn
    return p


def _write_pn_eq_tex(path: Path, p: Dict[int, sp.Expr]) -> None:
    """Write an aligned equation block for p_1..p_10."""
    u = sp.Symbol("u")
    lines: list[str] = []
    lines.append("% Generated by scripts/exp_sync_kernel_weighted_primitive_completed.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    for n in range(1, 11):
        expr = sp.expand(p[n])
        lhs = f"p_{n}(u)"
        rhs = sp.latex(expr)
        tail = "," if n != 10 else "."
        lines.append(f"{lhs}&={rhs}{tail}\\\\")
    lines.append("\\end{aligned}")
    lines.append("\\]")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_table_tex(path: Path, polys: Dict[int, sp.Expr]) -> None:
    lines: list[str] = []
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append(
        "\\caption{Completed primitive polynomials for the weighted sync-kernel. "
        "We define $u=r^2$, $s=r+r^{-1}$ and $\\widehat p_n(s):=r^{-n}p_n(r^2)\\in\\mathbb Z[s]$.}"
    )
    lines.append("\\label{tab:sync_kernel_weighted_primitive_completed}")
    lines.append("\\begin{tabular}{r l}")
    lines.append("\\toprule")
    lines.append("$n$ & $\\widehat p_n(s)$\\\\")
    lines.append("\\midrule")
    for n in sorted(polys.keys()):
        p = sp.expand(polys[n])
        lines.append(f"{n} & ${sp.latex(p)}$\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export completed primitive polynomials hat{p}_n(s).")
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_sync_kernel_weighted_primitive_completed.tex"),
        help="Output LaTeX table path.",
    )
    parser.add_argument(
        "--pn-eq-tex-out",
        type=str,
        default=str(generated_dir() / "eq_sync_kernel_weighted_primitive_pn_first10.tex"),
        help="Output LaTeX equation block for p_1..p_10.",
    )
    parser.add_argument(
        "--audit-json-out",
        type=str,
        default=str(generated_dir() / "audit_sync_kernel_weighted_dwork_coeffs.json"),
        help="Output JSON for coefficient-level Dwork defect checks (small n).",
    )
    args = parser.parse_args()

    u = sp.Symbol("u")
    Bu = _build_B_u(u)
    a = _trace_polys(Bu, N=10, u=u)
    p = _primitive_polys_from_traces(a, N=10, u=u)

    polys: Dict[int, sp.Expr] = {n: completed_poly_from_pn(n, p[n]) for n in range(2, 11)}
    write_table_tex(Path(args.tex_out), polys)
    _write_pn_eq_tex(Path(args.pn_eq_tex_out), p)
    print(f"[primitive-completed] wrote {args.tex_out}", flush=True)
    print(f"[primitive-completed] wrote {args.pn_eq_tex_out}", flush=True)

    # Coefficient-level Dwork defect audit for small n (within computed traces).
    # We check: Δ_{p,k}(u) = a_{p^k}(u) - a_{p^{k-1}}(u^p) has all coefficients divisible by p^k.
    audit_rows: list[dict] = []
    for p0 in (3, 5, 7, 11):
        k = 1
        while p0**k <= 10:
            n_pk = p0**k
            n_prev = p0 ** (k - 1)
            delta = sp.expand(a[n_pk] - a[n_prev].subs(u, u**p0))
            poly = sp.Poly(delta, u, domain=sp.ZZ)
            mod = p0**k
            coeffs = [int(c) for c in poly.all_coeffs()]  # highest degree first
            ok = all((c % mod) == 0 for c in coeffs)
            audit_rows.append(
                {
                    "p": int(p0),
                    "k": int(k),
                    "n": int(n_pk),
                    "mod": int(mod),
                    "delta_degree": int(poly.degree()) if poly.degree() is not None else 0,
                    "all_coeffs_divisible": bool(ok),
                }
            )
            k += 1

    audit_path = Path(args.audit_json_out)
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    audit_path.write_text(json.dumps({"N_traces": 10, "rows": audit_rows}, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[primitive-completed] wrote {audit_path}", flush=True)


if __name__ == "__main__":
    main()

