"""
Generate fiber-counting probability summary table for the paper:
docs/papers/math/2026_quantum_axioms_from_fiber_counting

Outputs:
  - sections/generated/fiber_counting_born_summary.tex

This script is intentionally self-contained (stdlib only).
It implements Fold_m by:
  b in {0,1}^m -> N(b)=sum_{i=1..m} b_i F_{i+1}
  -> Zeckendorf greedy digits z_2..z_{m+1}
  -> x=(z_2..z_{m+1}) in X_m (no adjacent ones)
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple


def fibs_upto(n: int) -> List[int]:
    """Return Fibonacci numbers F_0..F_n (inclusive)."""
    if n < 0:
        raise ValueError("n must be >= 0")
    fib = [0, 1]
    for _ in range(2, n + 1):
        fib.append(fib[-1] + fib[-2])
    return fib


def bits_of_int(x: int, m: int) -> List[int]:
    """Return length-m bits b_1..b_m (LSB = b_1)."""
    return [(x >> i) & 1 for i in range(m)]


def fold_m_from_bits(bits_b1_to_bm: List[int], fib: List[int]) -> int:
    """
    Compute Fold_m(b) as an integer bitmask for x in X_m:
    returns mask over positions 0..m-1 corresponding to z_2..z_{m+1}.
    """
    m = len(bits_b1_to_bm)
    # N(b) = sum_{i=1..m} b_i F_{i+1}, with b_1 as LSB.
    n = 0
    for i, bi in enumerate(bits_b1_to_bm, start=1):
        if bi:
            n += fib[i + 1]

    # Zeckendorf greedy for digits z_k, k = m+1 .. 2.
    # Constraint: no adjacent ones.
    remaining = n
    z = [0] * (m + 2)  # indices 0..m+1 used
    prev_one = False  # whether z_{k+1}=1 in descending loop
    for k in range(m + 1, 1, -1):
        if prev_one:
            # must set z_k=0
            z[k] = 0
            prev_one = False
            continue
        if fib[k] <= remaining:
            z[k] = 1
            remaining -= fib[k]
            prev_one = True
        else:
            z[k] = 0
            prev_one = False

    # Encode (z_2..z_{m+1}) into a mask with position (k-2).
    mask = 0
    for k in range(2, m + 2):
        if z[k]:
            mask |= 1 << (k - 2)
    return mask


def is_no_adjacent_ones_mask(mask: int) -> bool:
    return (mask & (mask >> 1)) == 0


def fib_count_xm(m: int) -> int:
    """|X_m| for 'no adjacent ones' words is F_{m+2}."""
    fib = fibs_upto(m + 2)
    return fib[m + 2]


@dataclass(frozen=True)
class SummaryRow:
    m: int
    xm: int
    fmin: int
    fmax: int
    hx: float
    hcond: float


def compute_fiber_summary(m: int) -> SummaryRow:
    fib = fibs_upto(m + 3)
    counts: Dict[int, int] = {}

    total = 1 << m
    last_print = time.time()
    for idx in range(total):
        bits = bits_of_int(idx, m)
        xmask = fold_m_from_bits(bits, fib=fib)
        # sanity: xmask should be no-adjacent by construction
        if not is_no_adjacent_ones_mask(xmask):
            raise RuntimeError(f"Fold produced adjacent ones (m={m}, idx={idx}, xmask={xmask})")
        counts[xmask] = counts.get(xmask, 0) + 1

        now = time.time()
        if now - last_print >= 20.0:
            pct = 100.0 * (idx + 1) / total
            print(f"[fiber_counting] m={m} progress: {idx+1}/{total} ({pct:.1f}%)", flush=True)
            last_print = now

    # Convert to probabilities p = count/2^m
    probs = [c / total for c in counts.values()]
    if abs(sum(probs) - 1.0) > 1e-12:
        raise RuntimeError(f"Probability normalization failed for m={m}: sum={sum(probs)}")

    # Shannon entropy base-2
    hx = 0.0
    for p in probs:
        hx -= p * math.log(p, 2)
    hcond = m - hx

    fmin = min(counts.values())
    fmax = max(counts.values())
    xm = fib_count_xm(m)
    return SummaryRow(m=m, xm=xm, fmin=fmin, fmax=fmax, hx=hx, hcond=hcond)


def format_row_tex(row: SummaryRow) -> str:
    return (
        f"{row.m} & {row.xm} & {row.fmin} & {row.fmax} & "
        f"{row.hx:.6f} & {row.hcond:.6f}\\\\"
    )


def project_root() -> Path:
    # scripts/ -> project root
    return Path(__file__).resolve().parents[1]


def generated_dir() -> Path:
    return project_root() / "sections" / "generated"


def main() -> None:
    ms = [10, 12, 14, 16]
    print(f"[fiber_counting] generating rows for m={ms}", flush=True)

    rows: List[SummaryRow] = []
    for m in ms:
        t0 = time.time()
        row = compute_fiber_summary(m)
        rows.append(row)
        dt = time.time() - t0
        print(
            f"[fiber_counting] done m={m} |X_m|={row.xm} "
            f"fmin={row.fmin} fmax={row.fmax} H={row.hx:.6f} Hcond={row.hcond:.6f} "
            f"({dt:.2f}s)",
            flush=True,
        )

    out_dir = generated_dir()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_tex = out_dir / "fiber_counting_born_summary.tex"

    lines = []
    lines.append("% Auto-generated by scripts/exp_fiber_counting_born_table.py")
    for r in rows:
        lines.append(format_row_tex(r))
    content = "\n".join(lines) + "\n"
    out_tex.write_text(content, encoding="utf-8")
    print(f"[fiber_counting] wrote: {out_tex}", flush=True)


if __name__ == "__main__":
    main()

