#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate collision-moment enumerations for Fold_m.

Outputs:
- artifacts/export/collision_moments.csv
- sections/generated/tab_collision_rates.tex

The generated LaTeX fragment is write-only and should be included via \\input.
"""

from __future__ import annotations

import argparse
import csv
import math
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

from common_paths import export_dir, generated_dir


@dataclass
class Progress:
    interval_s: float = 20.0
    t0: float = time.time()
    t_last: float = 0.0

    def log(self, msg: str) -> None:
        now = time.time()
        if (now - self.t_last) >= self.interval_s:
            dt = now - self.t0
            print(f"[progress] t={dt:.1f}s {msg}", flush=True)
            self.t_last = now


def fib_list(n: int) -> List[int]:
    """Return Fibonacci numbers F[0..n] with F_1=F_2=1 convention (F[0]=0)."""
    if n < 0:
        return []
    F = [0] * (n + 1)
    if n >= 1:
        F[1] = 1
    if n >= 2:
        F[2] = 1
    for k in range(3, n + 1):
        F[k] = F[k - 1] + F[k - 2]
    return F


def zeckendorf_digits_prefix(N: int, m: int, F: List[int]) -> int:
    """Return Fold_m of an integer value N as an m-bit mask.

Digit position k corresponds to weight F_{k+1}. The returned integer encodes
digits c_1..c_m as bits (c_k at bit k-1).
"""
    if N < 0:
        raise ValueError("N must be nonnegative")
    if m <= 0:
        return 0

    # Find maximal k such that F[k+1] <= N.
    k = 1
    while (k + 1) < len(F) and F[k + 1] <= N:
        k += 1
    if k > m + 4:
        # We only need prefix up to m; keeping a small buffer is safe.
        k = m + 4

    digits: Dict[int, int] = {}
    kk = k
    n = N
    while n > 0 and kk >= 1:
        w = F[kk + 1]
        if w <= n:
            digits[kk] = 1
            n -= w
            kk -= 2
        else:
            kk -= 1

    mask = 0
    for pos in range(1, m + 1):
        if digits.get(pos, 0):
            mask |= 1 << (pos - 1)
    return mask


def fold_m_mask(word: int, m: int, weights: List[int], F: List[int]) -> int:
    """Compute Fold_m for a binary microstate word encoded as bits."""
    N = 0
    w = word
    for k in range(1, m + 1):
        if w & 1:
            N += weights[k]
        w >>= 1
    return zeckendorf_digits_prefix(N, m, F)


def iter_binary_words(m: int) -> Iterable[int]:
    for w in range(1 << m):
        yield w


def collision_moments(m: int, k_list: List[int], prog: Progress) -> Dict[int, int]:
    """Compute S_k(m) for k in k_list by brute-force enumeration."""
    F = fib_list(m + 8)
    weights = [0] * (m + 1)
    for k in range(1, m + 1):
        weights[k] = F[k + 1]

    counts: Dict[int, int] = {}
    total = 1 << m
    for i, w in enumerate(iter_binary_words(m)):
        if (i & 0x3FFFF) == 0:
            prog.log(f"m={m} enumerate={i}/{total}")
        x = fold_m_mask(w, m, weights, F)
        counts[x] = counts.get(x, 0) + 1

    out: Dict[int, int] = {}
    for k in k_list:
        s = 0
        for c in counts.values():
            s += c**k
        out[k] = s
    return out


def write_csv(rows: List[Dict[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = list(rows[0].keys()) if rows else ["m", "k", "S_k", "rate_log"]
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def write_latex_table_rate(rows_by_m: Dict[int, Dict[int, int]], k_show: List[int], m_show: List[int], path: Path) -> None:
    """Generate a small LaTeX table fragment via pylatex."""
    from pylatex import Tabular, NoEscape  # type: ignore

    tab = Tabular("r|" + "r" * len(k_show))
    header = ["$m$"] + [f"$\\frac1m\\log S_{{{k}}}(m)$" for k in k_show]
    tab.add_hline()
    tab.add_row([NoEscape(h) for h in header])
    tab.add_hline()
    for m in m_show:
        row = [str(m)]
        for k in k_show:
            S = rows_by_m[m][k]
            row.append(f"{(math.log(S) / m):.6f}")
        tab.add_row(row)
    tab.add_hline()

    path.parent.mkdir(parents=True, exist_ok=True)
    tex = tab.dumps()
    # Wrap as a floating table only at the fragment level.
    frag = "\n".join(
        [
            "% auto-generated by scripts/gen_collision_moments.py",
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Empirical collision rates $\\frac1m\\log S_k(m)$ for small $m$ (brute-force over $\\Omega_m=\\{0,1\\}^m$).}",
            "\\label{tab:collision-rates}",
            tex,
            "\\end{table}",
            "",
        ]
    )
    path.write_text(frag, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--m-min", type=int, default=2)
    ap.add_argument("--m-max", type=int, default=18)
    ap.add_argument("--k", type=int, action="append", default=[2, 3], help="Collision orders k>=2 (repeatable).")
    ap.add_argument("--table-m-max", type=int, default=12, help="Max m included in the LaTeX table fragment.")
    args = ap.parse_args()

    m_min = int(args.m_min)
    m_max = int(args.m_max)
    if m_min < 1 or m_max < m_min:
        raise SystemExit("Invalid m range")
    k_list = sorted({int(k) for k in args.k})
    if not k_list or any(k < 2 for k in k_list):
        raise SystemExit("k must be >= 2")

    prog = Progress()
    rows: List[Dict[str, object]] = []
    rows_by_m: Dict[int, Dict[int, int]] = {}
    for m in range(m_min, m_max + 1):
        prog.log(f"start m={m}")
        sk = collision_moments(m, k_list, prog)
        rows_by_m[m] = sk
        for k in k_list:
            S = sk[k]
            rows.append(
                {
                    "m": m,
                    "k": k,
                    "S_k": S,
                    "rate_log": (math.log(S) / m),
                    "rate_log2": (math.log2(S) / m),
                    "S_over_2km": S / (2 ** (k * m)),
                }
            )
        prog.log(f"done m={m} " + " ".join([f"S{k}={sk[k]}" for k in k_list]))

    csv_path = export_dir() / "collision_moments.csv"
    write_csv(rows, csv_path)
    print(f"[gen] wrote {csv_path}", flush=True)

    m_show = [m for m in range(max(m_min, 2), min(m_max, int(args.table_m_max)) + 1)]
    if m_show:
        tex_path = generated_dir() / "tab_collision_rates.tex"
        write_latex_table_rate(rows_by_m, k_show=[k for k in k_list if k in (2, 3)], m_show=m_show, path=tex_path)
        print(f"[gen] wrote {tex_path}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

