# -*- coding: utf-8 -*-
"""
Proton mass -> resolution coordinate r(mu) and effective window m_eff (interface/matching helper).

Inputs:
  - data/pdg_minisets/proton_properties_miniset.json

Outputs (LaTeX fragments):
  - sections/generated/proton_resolution_mapping_rows.tex
  - sections/generated/proton_resolution_mapping_summary.tex

Design goals:
  - Deterministic output (no timestamps).
  - English-only output.
  - Standard-library only.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, List, Optional, Tuple

from common_constants import LOG_PHI, M_E_GEV, PHI
from common_paths import generated_dir, paper_root
from common_tex import write_lines


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


@dataclass(frozen=True)
class MapRow:
    obj: str
    mu_GeV: float
    r_mu: float
    r_step: float
    m_eff: int
    mu_th_lo: float
    mu_th_hi: float


def _r_of_mu(mu: float, mu0: float) -> float:
    return math.log(float(mu) / float(mu0)) / float(LOG_PHI)


def _mu_th(m: int, r_step: float) -> float:
    # V_40: r_th(m) = (m-6) * r_step, mu_th(m) = m_e * phi^{r_th(m)}.
    r_th = (int(m) - 6) * float(r_step)
    return float(M_E_GEV) * float(PHI ** float(r_th))


def _m_eff_from_r(r_mu: float, r_step: float) -> int:
    # V_40: m_eff(mu)=6+floor(r(mu)/r_step).
    return 6 + int(math.floor(float(r_mu) / float(r_step)))


def _load_proton_mass_GeV(path: Path) -> float:
    raw = _read_json(path)
    entries = raw.get("entries", [])
    # Prefer explicit id, then fall back to quantity+unit.
    for it in entries:
        if str(it.get("id", "")) == "proton_mass":
            return float(it["value"])
    for it in entries:
        if str(it.get("quantity", "")) == "mass" and str(it.get("unit", "")) == "GeV":
            return float(it["value"])
    raise RuntimeError("Could not find proton mass entry (id=proton_mass or quantity=mass unit=GeV).")


def _fmt(x: float, digits: int = 6) -> str:
    return f"{float(x):.{int(digits)}g}"


def _fmt_mu_GeV(mu: float) -> str:
    # Keep consistent with other tables: plain for typical GeV-scale values.
    if mu == 0.0:
        return "0"
    if mu < 1.0e-3 or mu >= 1.0e3:
        # scientific
        exp = int(math.floor(math.log10(abs(mu))))
        mant = float(mu) / (10.0**exp)
        return f"{mant:.6g}\\times 10^{{{exp}}}"
    return f"{float(mu):.10g}"


def main() -> None:
    r_step = 2.0 * math.pi
    data_path = paper_root() / "data" / "pdg_minisets" / "proton_properties_miniset.json"
    mu_p = _load_proton_mass_GeV(data_path)
    r_mu = _r_of_mu(mu_p, float(M_E_GEV))
    m_eff = _m_eff_from_r(r_mu, r_step)
    mu_lo = _mu_th(m_eff, r_step)
    mu_hi = _mu_th(m_eff + 1, r_step)

    row = MapRow(
        obj="proton",
        mu_GeV=float(mu_p),
        r_mu=float(r_mu),
        r_step=float(r_step),
        m_eff=int(m_eff),
        mu_th_lo=float(mu_lo),
        mu_th_hi=float(mu_hi),
    )

    lines: List[str] = []
    note = ""
    if row.m_eff == 8:
        note = "hadronic band (m=8)"
    elif row.m_eff == 7:
        note = "binding bridge (m=7)"
    elif row.m_eff < 7:
        note = "below binding benchmark"
    else:
        note = "above hadronic benchmark"

    lines.append(
        " & ".join(
            [
                row.obj,
                _fmt_mu_GeV(row.mu_GeV),
                _fmt(row.r_mu, 6),
                str(int(row.m_eff)),
                _fmt_mu_GeV(row.mu_th_lo),
                _fmt_mu_GeV(row.mu_th_hi),
                note,
            ]
        )
        + r" \\"
    )

    write_lines(generated_dir() / "proton_resolution_mapping_rows.tex", lines)

    summary = [
        r"\paragraph{Audit summary (proton $\mu\to r\to m_{\mathrm{eff}}$ mapping).} \AuditTag "
        r"We map the vendored proton mass $\mu_p$ (GeV) to the resolution coordinate "
        r"$r(\mu)=\log(\mu/m_e)/\log\varphi$ using $m_e=\texttt{M\_E\_GEV}$ and $\varphi=\texttt{PHI}$, "
        r"then compute $m_{\mathrm{eff}}(\mu)=6+\lfloor r(\mu)/r_{\mathrm{step}}\rfloor$ with "
        r"$r_{\mathrm{step}}=2\pi$ as in Section~\ref{sec:falsifiability_predictions}. "
        r"Rows are generated by \texttt{scripts/exp\_proton\_resolution\_mapping.py} from "
        r"\texttt{data/pdg\_minisets/proton\_properties\_miniset.json}.",
    ]
    write_lines(generated_dir() / "proton_resolution_mapping_summary.tex", summary)


if __name__ == "__main__":
    main()

