# -*- coding: utf-8 -*-
"""
Proton property miniset -> LaTeX fragments (matching/audit helper).

Inputs:
  - data/pdg_minisets/proton_properties_miniset.json

Outputs (LaTeX fragments):
  - sections/generated/proton_properties_rows.tex
  - sections/generated/proton_properties_summary.tex

Design goals:
  - Deterministic output (no timestamps).
  - English-only output.
  - Standard-library only.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, List, Optional

from common_paths import generated_dir, paper_root
from common_tex import write_lines


@dataclass(frozen=True)
class Entry:
    quantity: str
    value: float
    unit: str
    source: str


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _as_float(x: Any) -> float:
    return float(x)


def _as_str(x: Any) -> str:
    return str(x)


def _load_entries(path: Path) -> List[Entry]:
    raw = _read_json(path)
    items = raw.get("entries", [])
    out: List[Entry] = []
    for it in items:
        try:
            out.append(
                Entry(
                    quantity=_as_str(it["quantity"]),
                    value=_as_float(it["value"]),
                    unit=_as_str(it["unit"]),
                    source=_as_str(it.get("source", "")),
                )
            )
        except Exception:
            continue
    return out


def _fmt_value(x: float, digits: Optional[int] = None) -> str:
    # Keep it simple and deterministic: use repr-like formatting unless overridden.
    if digits is None:
        return f"{float(x):.10g}"
    return f"{float(x):.{int(digits)}g}"


def _row_lines(entries: Iterable[Entry]) -> List[str]:
    # Columns: quantity | value | unit | source
    lines: List[str] = []
    for e in entries:
        val = _fmt_value(e.value)
        qty = e.quantity.replace("_", r"\_")
        unit = e.unit.replace("_", r"\_")
        src = e.source.replace("_", r"\_")
        lines.append(" & ".join([qty, val, unit, src]) + r" \\")
    return lines if lines else ["% (no rows)"]


def main() -> None:
    data_path = paper_root() / "data" / "pdg_minisets" / "proton_properties_miniset.json"
    entries = _load_entries(data_path)

    write_lines(generated_dir() / "proton_properties_rows.tex", _row_lines(entries))

    summary = [
        r"\paragraph{Audit summary (proton property miniset).} \AuditTag "
        r"Rows are vendored matching-layer reference targets for the hydrogen nucleus (proton). "
        r"The JSON input is stored under \texttt{data/pdg\_minisets/proton\_properties\_miniset.json}; "
        r"this fragment is generated by \texttt{scripts/exp\_proton\_properties\_miniset.py}.",
    ]
    write_lines(generated_dir() / "proton_properties_summary.tex", summary)


if __name__ == "__main__":
    main()

