# -*- coding: utf-8 -*-
"""
Hydrogen atom miniset -> LaTeX fragments (matching/audit helper).

Inputs:
  - data/pdg_minisets/hydrogen_atom_miniset.json

Outputs (LaTeX fragments):
  - sections/generated/hydrogen_atom_rows.tex
  - sections/generated/hydrogen_atom_summary.tex

Design goals:
  - Deterministic output (no timestamps).
  - English-only output.
  - Standard-library only.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, List

from common_paths import generated_dir, paper_root
from common_tex import write_lines


@dataclass(frozen=True)
class Entry:
    quantity: str
    value: float
    unit: str
    source: str


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_entries(path: Path) -> List[Entry]:
    raw = _read_json(path)
    items = raw.get("entries", [])
    out: List[Entry] = []
    for it in items:
        try:
            out.append(
                Entry(
                    quantity=str(it["quantity"]),
                    value=float(it["value"]),
                    unit=str(it["unit"]),
                    source=str(it.get("source", "")),
                )
            )
        except Exception:
            continue
    return out


def _fmt_value(x: float) -> str:
    return f"{float(x):.10g}"


def _row_lines(entries: Iterable[Entry]) -> List[str]:
    lines: List[str] = []
    for e in entries:
        qty = e.quantity.replace("_", r"\_")
        unit = e.unit.replace("_", r"\_")
        src = e.source.replace("_", r"\_")
        lines.append(" & ".join([qty, _fmt_value(e.value), unit, src]) + r" \\")
    return lines if lines else ["% (no rows)"]


def main() -> None:
    data_path = paper_root() / "data" / "pdg_minisets" / "hydrogen_atom_miniset.json"
    entries = _load_entries(data_path)

    write_lines(generated_dir() / "hydrogen_atom_rows.tex", _row_lines(entries))

    summary = [
        r"\paragraph{Audit summary (hydrogen atom miniset).} \AuditTag "
        r"Rows are vendored matching-layer reference targets for the hydrogen atom. "
        r"The JSON input is stored under \texttt{data/pdg\_minisets/hydrogen\_atom\_miniset.json}; "
        r"this fragment is generated by \texttt{scripts/exp\_hydrogen\_atom\_miniset.py}.",
    ]
    write_lines(generated_dir() / "hydrogen_atom_summary.tex", summary)


if __name__ == "__main__":
    main()

