# -*- coding: utf-8 -*-
"""
Hydrogen spectral-line frequency -> omega -> time-scale bridge (phase/delay interface helper).

This script does NOT claim that atomic lines are scattering phase shifts.
It provides a disciplined, frequency-first bridge to the existing phase->delay
audit infrastructure: once a platform supplies a response phase phi(omega),
one can compute a Wigner--Smith-type delay proxy via dphi/domega.

Inputs:
  - data/pdg_minisets/hydrogen_spectral_lines_miniset.json

Outputs (LaTeX fragments):
  - sections/generated/hydrogen_spectral_delay_bridge_rows.tex
  - sections/generated/hydrogen_spectral_delay_bridge_summary.tex

Design goals:
  - Deterministic output (no timestamps).
  - English-only output.
  - Standard-library only.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, List

from common_paths import generated_dir, paper_root
from common_tex import write_lines


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt(x: float, sig: int = 8) -> str:
    return f"{float(x):.{int(sig)}g}"


def _fmt_sci(x: float) -> str:
    if x == 0.0:
        return "0"
    ax = abs(float(x))
    exp = int(math.floor(math.log10(ax)))
    mant = float(x) / (10.0**exp)
    return f"{mant:.6g}\\times 10^{{{exp}}}"


def _fmt_hz(f: float) -> str:
    # Frequencies here are typically large; format in scientific notation.
    return _fmt_sci(f) if (abs(float(f)) >= 1.0e6) else f"{float(f):.10g}"


def _fmt_seconds(t: float) -> str:
    # Periods will often be tiny; keep scientific form.
    return _fmt_sci(t) if (abs(float(t)) < 1.0e-3 or abs(float(t)) >= 1.0e3) else f"{float(t):.10g}"


@dataclass(frozen=True)
class Row:
    quantity: str
    f_hz: float
    omega: float
    period: float
    note: str


def main() -> None:
    data_path = paper_root() / "data" / "pdg_minisets" / "hydrogen_spectral_lines_miniset.json"
    raw = _read_json(data_path)
    entries = raw.get("entries", [])

    rows: List[Row] = []
    for it in entries:
        if str(it.get("unit", "")) != "Hz":
            continue
        q = str(it.get("quantity", "frequency"))
        f = float(it.get("value", 0.0))
        omega = 2.0 * math.pi * float(f)
        period = (1.0 / float(f)) if float(f) != 0.0 else float("inf")
        note = "spectral frequency (phase/delay bridge via omega)"
        if "21cm" in q:
            note = "hyperfine (phase/delay bridge via omega)"
        if "lyman_alpha" in q:
            note = "UV transition (phase/delay bridge via omega)"
        rows.append(Row(quantity=q, f_hz=f, omega=omega, period=period, note=note))

    # Stable deterministic ordering.
    rows_sorted = sorted(rows, key=lambda r: (r.quantity,))

    lines: List[str] = []
    for r in rows_sorted:
        qty = r.quantity.replace("_", r"\_")
        lines.append(
            " & ".join(
                [
                    qty,
                    _fmt_hz(r.f_hz),
                    _fmt_sci(r.omega),
                    _fmt_seconds(r.period),
                    r.note,
                ]
            )
            + r" \\"
        )

    write_lines(
        generated_dir() / "hydrogen_spectral_delay_bridge_rows.tex",
        lines if lines else ["% (no rows)"],
    )

    summary = [
        r"\paragraph{Audit summary (hydrogen spectral frequency$\to\omega$ bridge).} \AuditTag "
        r"For a spectral line with frequency $f$, define $\omega=2\pi f$ and period $T=1/f$. "
        r"Once a platform supplies a response phase $\phi(\omega)$ (e.g.\ via a complex transfer function), "
        r"the paper's standard phase$\to$delay step applies: $\tau(\omega)=\dd\phi/\dd\omega$ "
        r"(see Appendix~\ref{app:force_phase_delay_audit} and Appendix~\ref{app:k4_scattering_phase_delay_audit}). "
        r"Rows are generated by \texttt{scripts/exp\_hydrogen\_spectral\_phase\_delay\_bridge.py} from "
        r"\texttt{data/pdg\_minisets/hydrogen\_spectral\_lines\_miniset.json}.",
    ]
    write_lines(generated_dir() / "hydrogen_spectral_delay_bridge_summary.tex", summary)


if __name__ == "__main__":
    main()

