# -*- coding: utf-8 -*-
"""
Deterministic changepoint estimate for the full-fusion trapping transition proxy.

Given the metrics-only scan points (f_hor, Δτ) produced by
  scripts/exp_full_fusion_trapping_transition_scan.py
we fit a two-segment piecewise linear model and pick the split that minimizes SSE.

Outputs (LaTeX fragments):
  - sections/generated/full_fusion_trapping_transition_changepoint_summary.tex

Design:
  - deterministic; finite candidate splits; no randomness
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Tuple

from common_paths import generated_dir
from common_tex import write_lines


def _fmt(x: float, nd: int = 6) -> str:
    return f"{float(x):.{int(nd)}f}"


@dataclass(frozen=True)
class Point:
    f: float
    y: float


def _read_points_from_rows_tex() -> List[Point]:
    """
    Parse sections/generated/full_fusion_trapping_transition_scan_rows.tex
    which has rows: n & m_window & i_obs & c & f_hor & tau_free & tau_trap & delta_tau \\
    """
    path = generated_dir() / "full_fusion_trapping_transition_scan_rows.tex"
    txt = path.read_text(encoding="utf-8").splitlines()
    pts: List[Point] = []
    for line in txt:
        s = line.strip()
        if not s or s.startswith("%") or s.startswith("\\bottomrule"):
            continue
        # Remove trailing \\ if present.
        s = s.replace("\\\\", "").strip()
        parts = [p.strip() for p in s.split("&")]
        if len(parts) < 8:
            continue
        f = float(parts[4])
        y = float(parts[7])
        pts.append(Point(f=f, y=y))
    # Deterministic sort.
    pts.sort(key=lambda p: (p.f, p.y))
    return pts


def _fit_line(xs: List[float], ys: List[float]) -> Tuple[float, float, float]:
    """
    Fit y = a + b x by least squares.
    Returns (a, b, sse).
    """
    n = len(xs)
    if n <= 1:
        # Degenerate: treat as constant.
        a = ys[0] if ys else 0.0
        return float(a), 0.0, 0.0
    mx = sum(xs) / float(n)
    my = sum(ys) / float(n)
    sxx = sum((x - mx) ** 2 for x in xs)
    if sxx <= 0.0:
        a = my
        b = 0.0
    else:
        sxy = sum((x - mx) * (y - my) for (x, y) in zip(xs, ys))
        b = sxy / sxx
        a = my - b * mx
    sse = sum((y - (a + b * x)) ** 2 for (x, y) in zip(xs, ys))
    return float(a), float(b), float(sse)


def main() -> None:
    pts = _read_points_from_rows_tex()
    if len(pts) < 6:
        raise ValueError("Not enough points for a changepoint estimate; run the scan first.")

    xs = [p.f for p in pts]
    ys = [p.y for p in pts]

    # Candidate splits: ensure at least k points per side.
    k = 3
    best = None  # (sse, idx, params_left, params_right)
    for idx in range(k, len(xs) - k + 1):
        xl, yl = xs[:idx], ys[:idx]
        xr, yr = xs[idx:], ys[idx:]
        a1, b1, sse1 = _fit_line(xl, yl)
        a2, b2, sse2 = _fit_line(xr, yr)
        sse = sse1 + sse2
        # Deterministic tie-break: smaller sse, then smaller idx.
        cand = (sse, idx, (a1, b1, sse1), (a2, b2, sse2))
        if best is None or cand[0] < best[0] - 1e-15 or (abs(cand[0] - best[0]) <= 1e-15 and cand[1] < best[1]):
            best = cand

    if best is None:
        raise RuntimeError("No split candidates evaluated.")

    sse, idx, (a1, b1, sse1), (a2, b2, sse2) = best
    # Report changepoint as midpoint between boundary x-values.
    xL = xs[idx - 1]
    xR = xs[idx]
    f_star = 0.5 * (float(xL) + float(xR))

    # R^2 against global mean as a reader-friendly goodness proxy (still deterministic).
    ybar = sum(ys) / float(len(ys))
    sst = sum((y - ybar) ** 2 for y in ys)
    r2 = 1.0 - (sse / sst) if sst > 0.0 else float("nan")

    lines = [
        r"\paragraph{Deterministic changepoint estimate (full-fusion trapping transition).} "
        r"\AuditTag Using the scan points $(f_{\mathrm{hor}},\Delta\tau)$ generated in "
        r"\texttt{full\_fusion\_trapping\_transition\_scan\_rows.tex}, we fit a two-segment "
        r"piecewise linear model (least squares on each side) and select the split that minimizes "
        r"the total SSE over all admissible splits (at least 3 points per side). "
        + rf"The resulting changepoint estimate is $f_{{\mathrm{{hor}}}}^\star\approx {_fmt(f_star,6)}$, "
        + rf"with $(a_1,b_1)=({_fmt(a1,6)},{_fmt(b1,6)})$ and $(a_2,b_2)=({_fmt(a2,6)},{_fmt(b2,6)})$, "
        + rf"total SSE $\approx {_fmt(sse,6)}$ and $R^2\approx {_fmt(r2,6)}$ (relative to the global-mean baseline). "
        r"Generated by \texttt{scripts/exp\_full\_fusion\_trapping\_transition\_changepoint.py}."
    ]
    write_lines(generated_dir() / "full_fusion_trapping_transition_changepoint_summary.tex", lines)
    print("Wrote sections/generated/full_fusion_trapping_transition_changepoint_summary.tex")


if __name__ == "__main__":
    main()

