import Mathlib
#check div_le_div_iff
#check div_lt_iff
#check one_lt_div
#check Finset.sum_lt_sum
#check Finset.card_univ
#check Fin.sum_univ_eq_sum_range
#check abs_le
#check Int.floor_eq_iff
#check Rat.floor_le
#check Rat.lt_floor_add_one
#check Nat.ceil
