#!/usr/bin/env python3
"""
Enumerate X_m, C_m, B_m and validate counting identities.

Outputs:
  - artifacts/counts_check/<run_id>/counts_check.json
  - sections/generated/counts_check.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path
from typing import Dict, List

from common_artifacts import add_output_hashes, build_base_manifest, prepare_run, write_manifest
from common_paths import generated_dir
from common_progress import Progress
from common_zeckendorf import iter_cycle_no_adjacent_words, iter_no_adjacent_words


def fib_std(n: int) -> int:
    if n < 0:
        raise ValueError("n must be nonnegative")
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def lucas_std(n: int) -> int:
    if n < 0:
        raise ValueError("n must be nonnegative")
    a, b = 2, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def write_counts_table_tex(rows: List[Dict[str, int]], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_counts_check.py")
    lines.append("\\begin{tabular}{rrrrrrrrr}")
    lines.append("\\toprule")
    lines.append("$m$ & $|X_m|$ & $F_{m+2}$ & $|C_m|$ & $L_m$ & $|B_m|$ & $F_{m-2}$ & $|X_{2m}|$ & $|X_m|^2-F_m^2$\\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r['m']} & {r['X']} & {r['F_m2']} & {r['C']} & {r['L_m']} & {r['B']} & {r['F_m_2']} & {r['X_2m']} & {r['iface_loss']}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--m-max", type=int, default=24)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    script_path = Path(__file__).resolve()
    params = {"m_max": int(args.m_max)}
    run = prepare_run(
        experiment="counts_check",
        params=params,
        script_path=script_path,
        required_files=["counts_check.json"],
        force=bool(args.force),
    )

    out_json = run.run_dir / "counts_check.json"
    out_tex = generated_dir() / "counts_check.tex"

    if run.cached:
        print(f"[counts_check] cached: {run.run_dir}", flush=True)
        return

    prog = Progress(every_seconds=15.0)
    rows: List[Dict[str, int]] = []
    details: Dict[str, Dict[str, int]] = {}

    for m in range(1, args.m_max + 1):
        X_list = list(iter_no_adjacent_words(m))
        C_list = list(iter_cycle_no_adjacent_words(m))
        X = len(X_list)
        C = len(C_list)
        B = X - C

        F_m2 = fib_std(m + 2)
        L_m = lucas_std(m)
        F_m_2 = fib_std(m - 2) if m >= 2 else 0

        X_2m = len(list(iter_no_adjacent_words(2 * m)))
        iface_loss = (X * X) - (fib_std(m) ** 2)

        rows.append(
            {
                "m": m,
                "X": X,
                "F_m2": F_m2,
                "C": C,
                "L_m": L_m,
                "B": B,
                "F_m_2": F_m_2,
                "X_2m": X_2m,
                "iface_loss": iface_loss,
            }
        )
        details[str(m)] = rows[-1]
        prog.maybe(f"m={m}/{args.m_max} |X_m|={X}")

    payload = {"params": params, "rows": rows, "by_m": details}
    out_json.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")

    write_counts_table_tex(rows=rows, out_path=out_tex)

    manifest = build_base_manifest("counts_check", run.run_id, params=params, script_path=script_path)
    manifest = add_output_hashes(manifest, run.run_dir, ["counts_check.json"])
    write_manifest(run.run_dir, manifest)

    prog.done(f"wrote {out_json} and {out_tex}")


if __name__ == "__main__":
    main()

