#!/usr/bin/env python3
"""
Compute first-layer fiber spectrum for Fold_m (paper definition).

We enumerate all micro window states b in Omega_m = {0,1}^m, interpret them in Fibonacci weights,
then fold to macro words in X_m using Zeckendorf canonicalization and truncation.

Outputs:
  - artifacts/fiber_spectrum/<run_id>/summary.json
  - artifacts/fiber_spectrum/<run_id>/fiber_hist.png
  - sections/generated/fiber_entropy_summary.tex
"""

from __future__ import annotations

import argparse
import json
import math
from collections import Counter
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt

from common_artifacts import add_output_hashes, build_base_manifest, prepare_run, write_manifest
from common_paths import generated_dir
from common_progress import Progress
from common_zeckendorf import build_fold_domain, fold_window_bits_to_macro_word, word_bits_high_to_low_str


def entropy_base2_from_probs(ps: List[float]) -> float:
    h = 0.0
    for p in ps:
        if p > 0.0:
            h -= p * math.log(p, 2.0)
    return h


def write_entropy_summary_tex(m: int, stats: Dict[str, float], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_fiber_spectrum.py")
    lines.append("\\begin{tabular}{lr}")
    lines.append("\\toprule")
    lines.append("Quantity & Value\\\\")
    lines.append("\\midrule")
    lines.append(f"$m$ & {m}\\\\")
    lines.append(f"$H(X_m)$ & {stats['H_X']:.6f}\\\\")
    lines.append(f"$H(\\Omega_m\\mid X_m)$ & {stats['H_cond']:.6f}\\\\")
    lines.append(f"$\\max_x |\\mathcal{{F}}_m(x)|$ & {int(stats['fiber_max'])}\\\\")
    lines.append(f"$\\min_x |\\mathcal{{F}}_m(x)|$ & {int(stats['fiber_min'])}\\\\")
    lines.append(
        "$\\mathbb{E}_{x\\sim\\mathrm{Unif}(X_m)}[|\\mathcal{F}_m(x)|]$ & "
        + f"{stats['fiber_mean_unif']:.6f}\\\\"
    )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--m", type=int, default=16)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--max-show", type=int, default=10, help="How many top macro words to include in summary.json.")
    args = ap.parse_args()

    m = int(args.m)
    if m < 1:
        raise ValueError("m must be >= 1")

    script_path = Path(__file__).resolve()
    params = {"m": m}
    run = prepare_run(
        experiment="fiber_spectrum",
        params=params,
        script_path=script_path,
        required_files=["summary.json", "fiber_hist.png"],
        force=bool(args.force),
    )

    out_json = run.run_dir / "summary.json"
    out_png = run.run_dir / "fiber_hist.png"
    out_tex = generated_dir() / "fiber_entropy_summary.tex"

    if run.cached:
        print(f"[fiber_spectrum] cached: {run.run_dir}", flush=True)
        return

    prog = Progress(every_seconds=15.0)
    domain = build_fold_domain(m)

    counts: Counter[int] = Counter()
    n_micro = 1 << m
    for b in range(n_micro):
        x = fold_window_bits_to_macro_word(b, m=m)
        counts[x] += 1
        if (b & 0x3FFFF) == 0:
            prog.maybe(f"enumerating b={b}/{n_micro}")

    # Ensure all macro words are present (some may have zero fiber, but in this model Fold_m is onto X_m).
    fiber_sizes: List[int] = []
    for x in domain.macro_words:
        fiber_sizes.append(int(counts.get(x, 0)))

    ps = [c / float(n_micro) for c in fiber_sizes if c > 0]
    H_X = entropy_base2_from_probs(ps)
    H_cond = float(m) - H_X

    fiber_min = float(min(fiber_sizes)) if fiber_sizes else 0.0
    fiber_max = float(max(fiber_sizes)) if fiber_sizes else 0.0
    fiber_mean_unif = (sum(fiber_sizes) / float(len(fiber_sizes))) if fiber_sizes else 0.0

    # Plot histogram of fiber sizes.
    plt.figure(figsize=(7.0, 4.0))
    plt.hist(fiber_sizes, bins=50, color="#1f77b4", alpha=0.9)
    plt.title(f"Fiber size histogram (m={m})")
    plt.xlabel("|F_m(x)|")
    plt.ylabel("count of x")
    plt.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_png, dpi=160)
    plt.close()

    # Prepare summary.
    items = list(counts.items())
    items.sort(key=lambda kv: (-kv[1], kv[0]))
    top = [
        {"x_bits": word_bits_high_to_low_str(x, m), "x_int": int(x), "fiber_size": int(c)}
        for x, c in items[: int(args.max_show)]
    ]

    stats: Dict[str, float] = {
        "H_X": float(H_X),
        "H_cond": float(H_cond),
        "fiber_min": float(fiber_min),
        "fiber_max": float(fiber_max),
        "fiber_mean_unif": float(fiber_mean_unif),
    }
    payload = {
        "params": params,
        "n_micro": int(n_micro),
        "n_macro": int(len(domain.macro_words)),
        "stats": stats,
        "top_macro_words_by_fiber": top,
    }
    out_json.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")

    write_entropy_summary_tex(m=m, stats=stats, out_path=out_tex)

    manifest = build_base_manifest("fiber_spectrum", run.run_id, params=params, script_path=script_path)
    manifest = add_output_hashes(manifest, run.run_dir, ["summary.json", "fiber_hist.png"])
    write_manifest(run.run_dir, manifest)

    prog.done(f"wrote {out_json}, {out_png}, and {out_tex}")


if __name__ == "__main__":
    main()

