#!/usr/bin/env python3
"""
Compute first-layer fiber spectrum for Fold_m (paper definition).

We enumerate all micro window states b in Omega_m = {0,1}^m, interpret them in Fibonacci weights,
then fold to macro words in X_m using Zeckendorf canonicalization and truncation.

Outputs:
  - artifacts/fiber_spectrum/<run_id>/summary.json
  - artifacts/fiber_spectrum/<run_id>/fiber_hist.png
  - sections/generated/fiber_entropy_summary_<trunc>.tex
"""

from __future__ import annotations

import argparse
import json
import math
from collections import Counter
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt

from common_artifacts import add_output_hashes, build_base_manifest, prepare_run, write_manifest
from common_export import copy_atomic
from common_paths import generated_dir
from common_progress import Progress
from common_pylatex import NoEscape, booktabs_tabular, write_tex_fragment
from common_zeckendorf import build_fold_domain, word_bits_high_to_low_str
from truncations import available_truncations, get_truncation


def entropy_base2_from_probs(ps: List[float]) -> float:
    h = 0.0
    for p in ps:
        if p > 0.0:
            h -= p * math.log(p, 2.0)
    return h


def write_entropy_summary_tex(m: int, truncation: str, stats: Dict[str, float], out_path: Path) -> None:
    tab = booktabs_tabular(
        col_spec="l r",
        header=[NoEscape("Quantity"), NoEscape("Value")],
        rows=[
            [NoEscape(r"$m$"), str(m)],
            [NoEscape(r"truncation"), NoEscape(rf"\texttt{{{truncation}}}")],
            [NoEscape(r"$H(X_m)$"), f"{stats['H_X']:.6f}"],
            [NoEscape(r"$H(\Omega_m\mid X_m)$"), f"{stats['H_cond']:.6f}"],
            [NoEscape(r"$H(U_m)$"), f"{stats['H_U']:.6f}"],
            [NoEscape(r"$H(U_m\mid X_m)$"), f"{stats['H_U_given_X']:.6f}"],
            [NoEscape(r"$\max_x |\mathcal{F}_m(x)|$"), str(int(stats["fiber_max"]))],
            [NoEscape(r"$\min_x |\mathcal{F}_m(x)|$"), str(int(stats["fiber_min"]))],
            [
                NoEscape(r"$\mathbb{E}_{x\sim\mathrm{Unif}(X_m)}[|\mathcal{F}_m(x)|]$"),
                f"{stats['fiber_mean_unif']:.6f}",
            ],
            [NoEscape(r"$\mathbb{E}_{x\sim p_m}[\#\mathrm{supp}(U_m\mid x)]$"), f"{stats['u_support_mean_px']:.6f}"],
        ],
    )
    write_tex_fragment(out_path, tab, comment="Auto-generated by scripts/exp_fiber_spectrum.py")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--m", type=int, default=16)
    ap.add_argument("--truncation", type=str, default="zeck_window", choices=list(available_truncations()))
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--max-show", type=int, default=10, help="How many top macro words to include in summary.json.")
    args = ap.parse_args()

    m = int(args.m)
    truncation = str(args.truncation)
    if m < 1:
        raise ValueError("m must be >= 1")

    script_path = Path(__file__).resolve()
    params = {"m": m, "truncation": truncation}
    run = prepare_run(
        experiment="fiber_spectrum",
        params=params,
        script_path=script_path,
        required_files=["summary.json", "fiber_hist.png", "fiber_entropy_summary.tex", "fiber_entropy_summary.json"],
        force=bool(args.force),
    )

    out_json = run.run_dir / "summary.json"
    out_png = run.run_dir / "fiber_hist.png"
    out_run_tex = run.run_dir / "fiber_entropy_summary.tex"
    out_run_gen_json = run.run_dir / "fiber_entropy_summary.json"
    out_tex = generated_dir() / f"fiber_entropy_summary_{truncation}.tex"
    out_gen_json = generated_dir() / f"fiber_entropy_summary_{truncation}.json"

    if run.cached:
        print(f"[fiber_spectrum] cached: {run.run_dir}", flush=True)
        copy_atomic(out_run_tex, out_tex)
        copy_atomic(out_run_gen_json, out_gen_json)
        return

    prog = Progress(every_seconds=15.0)
    domain = build_fold_domain(m)
    tr = get_truncation(truncation)

    counts: Counter[int] = Counter()
    counts_u: Counter[int] = Counter()
    counts_xu: Counter[Tuple[int, int]] = Counter()
    x_to_u: Dict[int, Counter[int]] = {}
    n_micro = 1 << m
    for b in range(n_micro):
        x = tr.space_word(b, m=m)
        u = tr.time_residual(b, m=m, x=x)
        counts[x] += 1
        counts_u[u] += 1
        counts_xu[(x, u)] += 1
        if x not in x_to_u:
            x_to_u[x] = Counter()
        x_to_u[x][u] += 1
        if (b & 0x3FFFF) == 0:
            prog.maybe(f"enumerating b={b}/{n_micro}")

    # Ensure all macro words are present (some may have zero fiber, but in this model Fold_m is onto X_m).
    fiber_sizes: List[int] = []
    for x in domain.macro_words:
        fiber_sizes.append(int(counts.get(x, 0)))

    ps = [c / float(n_micro) for c in fiber_sizes if c > 0]
    H_X = entropy_base2_from_probs(ps)
    H_cond = float(m) - H_X

    # Time residual entropies.
    pu = [c / float(n_micro) for c in counts_u.values() if c > 0]
    H_U = entropy_base2_from_probs(pu)

    # H(U|X) = sum_x p(x) H(U|x)
    H_U_given_X = 0.0
    u_support_weighted = 0.0
    for x in domain.macro_words:
        cx = float(counts.get(x, 0))
        if cx <= 0.0:
            continue
        cu = x_to_u.get(x, Counter())
        us = [float(c) / cx for c in cu.values() if c > 0]
        supp = len(cu)
        H_U_given_X += (cx / float(n_micro)) * entropy_base2_from_probs(us)
        u_support_weighted += (cx / float(n_micro)) * float(supp)

    fiber_min = float(min(fiber_sizes)) if fiber_sizes else 0.0
    fiber_max = float(max(fiber_sizes)) if fiber_sizes else 0.0
    fiber_mean_unif = (sum(fiber_sizes) / float(len(fiber_sizes))) if fiber_sizes else 0.0

    # Plot histogram of fiber sizes.
    plt.figure(figsize=(7.0, 4.0))
    plt.hist(fiber_sizes, bins=50, color="#1f77b4", alpha=0.9)
    plt.title(f"Fiber size histogram (m={m})")
    plt.xlabel("|F_m(x)|")
    plt.ylabel("count of x")
    plt.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_png, dpi=160)
    plt.close()

    # Prepare summary.
    items = list(counts.items())
    items.sort(key=lambda kv: (-kv[1], kv[0]))
    top = [
        {"x_bits": word_bits_high_to_low_str(x, m), "x_int": int(x), "fiber_size": int(c)}
        for x, c in items[: int(args.max_show)]
    ]

    stats: Dict[str, float] = {
        "H_X": float(H_X),
        "H_cond": float(H_cond),
        "H_U": float(H_U),
        "H_U_given_X": float(H_U_given_X),
        "u_support_mean_px": float(u_support_weighted),
        "fiber_min": float(fiber_min),
        "fiber_max": float(fiber_max),
        "fiber_mean_unif": float(fiber_mean_unif),
    }
    payload = {
        "params": params,
        "n_micro": int(n_micro),
        "n_macro": int(len(domain.macro_words)),
        "stats": stats,
        "top_macro_words_by_fiber": top,
    }
    out_json.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    out_run_gen_json.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    out_gen_json.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")

    write_entropy_summary_tex(m=m, truncation=truncation, stats=stats, out_path=out_run_tex)
    copy_atomic(out_run_tex, out_tex)

    manifest = build_base_manifest("fiber_spectrum", run.run_id, params=params, script_path=script_path)
    manifest = add_output_hashes(manifest, run.run_dir, ["summary.json", "fiber_hist.png"])
    write_manifest(run.run_dir, manifest)

    prog.done(f"wrote {out_json}, {out_png}, and {out_tex}")


if __name__ == "__main__":
    main()

